export const CROP_ICONS: { [key: string]: string } = {
    "Ajwan": "🌿",
    "Alasande Gram": "🫘",
    "Amaranthus": "🥬",
    "Amla(Nelli Kai)": "🟢",
    "Amranthas Red": "🍂",
    "Apple": "🍎",
    "Arecanut(Betelnut/Supari)": "🌴",
    "Arhar Dal(Tur Dal)": "🟡",
    "Arhar(Tur/Red Gram)(Whole)": "🟤",
    "Asalia": "🌱",
    "Asgand": "🌿",
    "Ashgourd": "🍈",
    "Astera": "🌸",
    "Bajra(Pearl Millet/Cumbu)": "🌾",
    "Banana": "🍌",
    "Banana - Green": "🍌",
    "Barley(Jau)": "🌾",
    "basil": "🌿",
    "Beans": "🫘",
    "Beetroot": "🍠",
    "Bengal Gram Dal(Chana Dal)": "🟡",
    "Bengal Gram(Gram)(Whole)": "🟤",
    "Ber(Zizyphus/Borehannu)": "🔴",
    "Betal Leaves": "🍃",
    "Bhindi(Ladies Finger)": "🥒",
    "Bitter gourd": "🥒",
    "Black Gram Dal(Urd Dal)": "⚫",
    "Black Gram(Urd Beans)(Whole)": "⚫",
    "Black pepper": "⚫",
    "Bottle gourd": "🍐",
    "Brinjal": "🍆",
    "Bunch Beans": "🫘",
    "buttery": "🧈",
    "Cabbage": "🥬",
    "Capsicum": "🫑",
    "Carrot": "🥕",
    "Castor Seed": "🌱",
    "Cauliflower": "🥦",
    "Chapparad Avare": "🫘",
    "Chikoos(Sapota)": "🥔",
    "Chili Red": "🌶️",
    "Chilly Capsicum": "🫑",
    "Chow Chow": "🍐",
    "Chrysanthemum": "🌼",
    "Cluster beans": "🫘",
    "Coconut": "🥥",
    "Coconut Oil": "🥥",
    "Coconut Seed": "🥥",
    "Coffee": "☕",
    "Colacasia": "🍠",
    "Copra": "🥥",
    "Coriander(Leaves)": "🌿",
    "Corriander seed": "🤎",
    "Cotton": "☁️",
    "Cowpea(Lobia/Karamani)": "🫘",
    "Cowpea(Veg)": "🫘",
    "Cucumbar(Kheera)": "🥒",
    "Cummin Seed(Jeera)": "🌱",
    "Custard Apple(Sharifa)": "🍏",
    "Delha": "🌱",
    "Dhaincha": "🌿",
    "Drumstick": "🥢",
    "Dry Chillies": "🌶️",
    "Elephant Yam(Suran)/Amorphophallus": "🪨",
    "Field Pea": "🟢",
    "Fig(Anjura/Anjeer)": "🍩",
    "Fish": "🐟",
    "French Beans(Frasbean)": "🫘",
    "Galgal(Lemon)": "🍋",
    "Garlic": "🧄",
    "Ghee": "🧈",
    "Ginger(Dry)": "🫚",
    "Ginger(Green)": "🫚",
    "Goat": "🐐",
    "Gram Raw(Chholia)": "🟢",
    "Grapes": "🍇",
    "Green Avare(W)": "🫘",
    "Green Chilli": "🌶️",
    "Green Fodder": "🌿",
    "Green Gram Dal(Moong Dal)": "🟡",
    "Green Gram(Moong)(Whole)": "🟢",
    "Green Peas": "🟢",
    "Ground Nut Seed": "🥜",
    "Groundnut": "🥜",
    "Groundnut(Split)": "🥜",
    "Guar": "🫘",
    "Guar Seed(Cluster Beans Seed)": "🫘",
    "Guava": "🍈",
    "Gur(Jaggery)": "🟤",
    "Indian Beans(Seam)": "🫘",
    "Indian Colza(Sarson)": "🌼",
    "Isabgul(Psyllium)": "🌾",
    "Jack Fruit": "🍈",
    "Jaggery": "🟤",
    "Jowar(Sorghum)": "🌾",
    "Jute": "🧶",
    "Kabuli Chana(Chickpeas-White)": "⚪",
    "Karbuja(Musk Melon)": "🍈",
    "Kinnow": "🍊",
    "Knool Khol": "🥬",
    "Kulthi(Horse Gram)": "🟤",
    "Kutki": "🌾",
    "Ladies Finger": "🥒",
    "Lak(Teora)": "🌱",
    "Leafy Vegetable": "🥬",
    "Lemon": "🍋",
    "Lentil(Masur)(Whole)": "🔴",
    "Lime": "🍋",
    "Linseed": "🌱",
    "Little gourd(Kundru)": "🥒",
    "Long Melon(Kakri)": "🥒",
    "Mahua": "🌸",
    "Maida Atta": "🍚",
    "Maize": "🌽",
    "Mango": "🥭",
    "Mango(Raw-Ripe)": "🥭",
    "Marigold(Calcutta)": "🌼",
    "Marigold(loose)": "🌼",
    "Mashrooms": "🍄",
    "Masur Dal": "🔴",
    "Mataki": "🫘",
    "Methi Seeds": "🟤",
    "Methi(Leaves)": "🌿",
    "Mint(Pudina)": "🌿",
    "Mousambi(Sweet Lime)": "🍊",
    "Mustard": "🌼",
    "Mustard Oil": "🛢️",
    "nigella": "⚫",
    "Onion": "🧅",
    "Onion Green": "🧅",
    "Orange": "🍊",
    "Paddy(Basmati)": "🌾",
    "Paddy(Common)": "🌾",
    "Papaya": "🥭",
    "Papaya(Raw)": "🥭",
    "Pear(Marasebu)": "🍐",
    "Peas cod": "🫛",
    "Peas Wet": "🟢",
    "Pegeon Pea(Arhar Fali)": "🫛",
    "Pineapple": "🍍",
    "Pointed gourd(Parval)": "🥒",
    "Pomegranate": "🍎",
    "poppy seeds": "⚪",
    "Potato": "🥔",
    "Pumpkin": "🎃",
    "Raddish": "🥕",
    "Ragi(Finger Millet)": "🌾",
    "Rajgir": "🌾",
    "Rayee": "⚫",
    "Red Gram": "🔴",
    "Rice": "🍚",
    "Ridgeguard(Tori)": "🥒",
    "Rose(Local)": "🌹",
    "Round gourd": "🍈",
    "Rubber": "🌳",
    "Safflower": "🌻",
    "Seemebadnekai": "🍐",
    "Sesamum(Sesame,Gingelly,Til)": "🌱",
    "Snakeguard": "🐍",
    "Soanf": "🌿",
    "Soyabean": "🌱",
    "Spinach": "🥬",
    "Sponge gourd": "🥒",
    "Squash(Chappal Kadoo)": "🥒",
    "Sugar": "🍚",
    "Sunflower": "🌻",
    "Surat Beans(Papadi)": "🫘",
    "Suvarna Gadde": "🍠",
    "Sweet Potato": "🍠",
    "Sweet Pumpkin": "🎃",
    "Tamarind Fruit": "🟤",
    "Tapioca": "🍠",
    "Taro (Arvi) Stem": "🌿",
    "Tender Coconut": "🥥",
    "Thogrikai": "🫛",
    "Thondekai": "🥒",
    "Tinda": "🍏",
    "Tomato": "🍅",
    "Tube Flower": "🌸",
    "Tube Rose(Loose)": "🌸",
    "Turmeric": "🟡",
    "Turmeric(raw)": "🫚",
    "Turnip": "⚪",
    "Water chestnut": "🌰",
    "Water Melon": "🍉",
    "Wheat": "🌾",
    "White Peas": "⚪",
    "Wood": "🪵",
    "Yam(Ratalu)": "🍠"
};
